
name: action CI

on: [push]

defaults:
  run:
    shell: bash

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker_image: sunny4249/ci-action-test:latest
            name: action (Python 3.8, backend)
            os: focal

    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    container: ${{ matrix.docker_image }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
            ls -al
            pwd
      - name: Workflow Dispatch
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Install dependencies
        run: |
            python3 -m venv /__w/action-ci/venv
            source /__w/action-ci/venv/bin/activate
            pip install --upgrade pip
            pip install --upgrade setuptools
            pip install -e .
      - name: start elasticsearch
        run: |
           service elasticsearch start
      - name: check elasticsearch connection
        run: |
          curl -XGET "http://localhost:9200"
      - name: Run pip list
        run: |
            pip list
      - name: Run tools test
        run: |
            source /__w/action-ci/venv/bin/activate
            bash ./scripts/run_test


