
name: action CI

on: [push]

defaults:
  run:
    shell: bash

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker_image: sunny4249/ci-action-test:latest
            name: action (Python 3.8, backend)
            os: focal

    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    container: ${{ matrix.docker_image }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
            ls -al
            pwd
      - name: Install dependencies
        run: |
            pip install -e .
      - name: Run pip list
        run: |
            pip list
      - name: echo context
        run: |
            echo "$GITHUB_CONTEXT"
      - name: Run tools test
        run: |
            bash ./scripts/run_test


